services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: freee
    ports:
      - '5432:5432'
    volumes:
      - ./docker_volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./docker_volumes/pgadmin_data:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - backend

  redis:
    image: redis:8.4.0-alpine
    container_name: marketplace-redis
    ports:
      - '6379:6379'
    volumes:
      - ./docker_volumes/redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - backend

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - '5540:5540'
    volumes:
      - ./docker_volumes/redis_insight_data:/data
    networks:
      - backend
    depends_on:
      - redis

networks:
  backend:
    driver: bridge
