services:
  - type: web
    name: free-backend-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node --max-old-space-size=450 dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

      # Database Connection (User to provide in Render Dashboard)
      - key: DATABASE_URL
        sync: false

      # Upstash Redis Connection (User to provide in Render Dashboard)
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false

      # Other Secrets (User to provide in Render Dashboard)
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
